services:
  # Service cho ứng dụng Next.js
  next-app:
    # Build image từ Dockerfile trong thư mục hiện tại
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nextjs_app_container
    restart: always # Tự động khởi động lại nếu bị lỗi
    networks:
      - app-network

  # Service cho Nginx Reverse Proxy
  nginx:
    image: nginx:alpine
    container_name: nginx_proxy_container
    restart: always
    ports:
      - "80:80"   # Ánh xạ cổng 80 của VPS vào cổng 80 của container
      - "443:443" # Ánh xạ cổng 443 của VPS vào cổng 443 của container
    volumes:
      # Ánh xạ file cấu hình Nginx
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      # Ánh xạ thư mục chứa chứng chỉ SSL từ Certbot
      - /etc/letsencrypt:/etc/letsencrypt
    depends_on:
      - next-app # Khởi chạy Nginx sau khi next-app đã sẵn sàng
    networks:
      - app-network

# Định nghĩa network để các container có thể giao tiếp với nhau
networks:
  app-network:
    driver: bridge